# Generated by Django 5.2.1 on 2025-06-04 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_systemstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemMetrics',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
