# Generated by Django 5.2.1 on 2025-06-04 05:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_delete_systemmetrics_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('cpu_usage', models.FloatField(help_text='CPU使用率(%)')),
                ('cpu_load_1', models.FloatField(help_text='1分钟平均负载')),
                ('cpu_load_5', models.FloatField(help_text='5分钟平均负载')),
                ('cpu_load_15', models.FloatField(help_text='15分钟平均负载')),
                ('mem_total', models.BigIntegerField(help_text='总内存(字节)')),
                ('mem_used', models.BigIntegerField(help_text='已用内存(字节)')),
                ('mem_free', models.BigIntegerField(help_text='空闲内存(字节)')),
                ('mem_usage', models.FloatField(help_text='内存使用率(%)')),
                ('disk_total', models.BigIntegerField(help_text='总磁盘空间(字节)')),
                ('disk_used', models.BigIntegerField(help_text='已用磁盘空间(字节)')),
                ('disk_free', models.BigIntegerField(help_text='空闲磁盘空间(字节)')),
                ('disk_usage', models.FloatField(help_text='磁盘使用率(%)')),
                ('net_sent', models.BigIntegerField(help_text='发送字节数')),
                ('net_recv', models.BigIntegerField(help_text='接收字节数')),
            ],
            options={
                'verbose_name': '系统指标',
                'verbose_name_plural': '系统指标',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='SystemStatus',
        ),
    ]
