# Generated by Django 5.2.1 on 2025-06-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_systemmetrics_test_delete_systemstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=210),
        ),
    ]
