# Generated by Django 5.2.1 on 2025-06-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_alter_test_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
